#! python3
print("'\\n' == chr(10)", '\n' == chr(10))
print("'\\\"' == chr(34)", '\"' == chr(34))
print("'\\\'' == chr(34)", '\'' == chr(39))
print("'\\t' == chr(34)", '\t' == chr(9))
print("'\\\\' == chr(34)", '\\' == chr(92))
print('\n')
print(r"'\n' == chr(10)", '\n' == chr(10))
print(r"'\"' == chr(34)", '\"' == chr(34))
print(r"'\'' == chr(34)", '\'' == chr(39))
print(r"'\t' == chr(34)", '\t' == chr(9))
print(r"'\\' == chr(34)", '\\' == chr(92))
print('\n')
print('------------.isX----------------')
print('hello123'.isalpha())
print('hello123'.isalnum())
print('123'.isdecimal())
print('    '.isspace())
print('This Is Title Case'.istitle())
print('\n')
print('------------join,split----------------')
print(','.join(['My', 'name', 'is', 'Simon']))
print('MyABCnameABCisABCSimon'.split('ABC'))
print('\n')
print('------------rjust(), ljust(), and center()----------------')
def printPicnic(itemsDict, leftWidth, rightWidth):
    print('PICNIC ITEMS'.center(leftWidth + rightWidth, '-'))
    for k, v in itemsDict.items():
        print(k.ljust(leftWidth, '.') + str(v).rjust(rightWidth,'-'))
picnicItems = {'sandwiches': 4, 'apples': 12, 'cups': 4, 'cookies': 8000}
printPicnic(picnicItems, 12, 5)
printPicnic(picnicItems, 20, 6)
print('\n')
print('------------strip(), rstrip(), and lstrip()----------------')
print('SpamSpamBaconSpamEggsSpamSpam'.rstrip('Spam'))
print('\n')
print('------------pyperclip----------------')
import pyperclip
print('inpuy pyperclip.copy:')
pause = input()
pyperclip.copy(pause)
pyperclip.paste()
